'use strict';
(async()=>{
  const API='https://yuukichiya-purchase-history-prototype.onrender.com/api/public-product-review/answers';
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s||'').normalize('NFKC').replace(/\s/g,'').toLowerCase();
  const words=/([（(][^）)]*[）)]|ファインレーベル|スリムスタイル|ノーアイロンプラス|開襟シャツ|パノラマ|バッグイン|レインスーツ|ジェンダーレス|セパレート水着|バイオレットブルー|ホワイト|オールシーズン|アドバンススポーツ|ストレートパンツ|スクールモード|男女兼用|ハーフパンツ|カッターシャツ|フルネーム|ブレザー|スラックス|ジャージ|スカート|セーラー|ポロシャツ|体操服|スリッパ|シューズ|カンコー|女子|男子|長袖|半袖)/g;
  const phrase=v=>String(v||'').split(/\s+/).map(part=>part.split(words).filter(Boolean).map(p=>`<span class="phrase">${esc(p)}</span>`).join('')).join(' ');
  let D,model,storage,state,pending=null,ready=false,busy=false,revision=-1,polling=false,view='questions',notice='';
  let session={reviewer:'端末-'+crypto.randomUUID().replace(/-/g,'').slice(0,6),mode:'match',salesOnly:true,store:'',school:'',page:0,cursor:0,history:[]};
  let pageBlocks=[],soloBlocks=[],completed=new Set(),savedGroups=new Map(),selection={},split=new Set(),pickerProduct=null,latest=null,pageStamps=new Map(),changedGroups=new Set();
  const error=message=>{$('#error').textContent=message;$('#error').hidden=!message;};
  const mark=text=>$('#save-status').textContent=text;
  function options(){return {salesOnly:session.salesOnly,store:session.store,school:session.school};}
  function queues(){return model.queues(state,options());}
  function eligible(q){return session.mode==='held'?q.blocks.filter(g=>g.status==='hold'):q.blocks.filter(g=>g.status!=='hold');}
  function reorder(blocks){return [...blocks].sort((a,b)=>Number(!!a.warnings.length)-Number(!!b.warnings.length)||Number(b.members.filter(k=>model.products.get(k).image).length)-Number(a.members.filter(k=>model.products.get(k).image).length)||Number(b.members.some(k=>model.products.get(k).source==='base'))-Number(a.members.some(k=>model.products.get(k).source==='base'))||a.school.localeCompare(b.school,'ja'));}
  function remember(){if(!storage)return;try{storage.saveSession(session);}catch{notice='回答は共有保存されています。端末の再開位置の控えは残せません。';}}
  function stamp(g){return model.canonical(g.members.flatMap((a,i)=>g.members.slice(i+1).flatMap(b=>model.heads(model.pairKey(a,b),state).map(e=>e.id))).sort());}
  function currentList(){const q=queues();return session.mode==='single'?q.solos.filter(s=>s.status!=='done'):reorder(eligible(q));}
  function newPage(start){
    if(!['match','held','single'].includes(session.mode)){remember();return;}
    const list=currentList(),size=session.mode==='single'?10:3;
    session.cursor=ReviewUI.position(list,session,start);session.page=Math.floor(session.cursor/size);
    session.resume=ReviewUI.capture(list,session.mode,session.cursor);
    if(session.mode==='single')soloBlocks=list.slice(session.cursor,session.cursor+size);
    else{pageBlocks=list.slice(session.cursor,session.cursor+size);pageStamps=new Map(pageBlocks.map(g=>[g.id,stamp(g)]));changedGroups=new Set();completed=new Set();savedGroups=new Map();selection={};split=new Set();}
    remember();
  }
  function openHistory(){if(busy||pending)return;if(session.mode!=='history')session.returnTo={mode:session.mode,page:session.page,cursor:session.cursor,resume:session.resume};session.mode='history';session.page=0;remember();tab('questions');window.scrollTo({top:0});}
  function resumeReview(){if(busy||pending)return;Object.assign(session,session.returnTo||{mode:'match',page:0,cursor:0});delete session.returnTo;newPage();tab('questions');window.scrollTo({top:0});}
  function savedNotice(events,recovered=false){$('#answer-message').textContent=(recovered?'前回の回答を保存しました：':'保存しました：')+ReviewUI.summary(events);$('#answer-notice').hidden=false;}
  function tab(name){view=name;$('#overview-panel').hidden=name!=='overview';$('#questions-panel').hidden=name!=='questions';for(const n of ['overview','questions'])$('#tab-'+n).setAttribute('aria-selected',String(n===name));render();}
  function card(key,block,selectable=false){const p=model.products.get(key),chosen=(selection[block?.id]||[]).includes(key);const photo=p.image?`<button class="photo-button" data-photo="${esc(key)}" aria-label="${esc(p.name)}の画像を拡大"><img src="${esc(p.image)}" alt="${esc(p.name)}" width="320" height="320" loading="lazy" decoding="async"></button>`:'<div class="placeholder">画像なし</div>';return `<article class="product ${chosen?'selected':''}" data-product="${esc(key)}"><p class="source"><span class="${p.source==='base'?'base-label':''}">${esc(p.store)}</span></p>${photo}<p class="product-name">${phrase(p.name)}</p>${block&&new Set(block.members.flatMap(k=>model.products.get(k).cats)).size>1?`<p class="product-school">${phrase(p.cats.join(' / '))}</p>`:''}<button class="details-button" data-details="${esc(key)}">詳しい情報</button>${selectable?`<button class="selection-button" data-select="${esc(key)}" data-block="${esc(block.id)}" aria-pressed="${chosen}">${chosen?'違う側に選択済み':'違う側に選ぶ'}</button>`:''}</article>`;}
  function layout(){for(const c of document.querySelectorAll('.product')){const parent=c.closest('.solo-wrapper')||c;parent.classList.remove('wide');const box=c.querySelector('.product-name');if(box&&[...box.querySelectorAll('.phrase')].some(p=>p.scrollWidth>box.clientWidth+1))parent.classList.add('wide');}}
  function renderOverview(q){const air=D.products.filter(p=>p.source==='air'),pendingGroups=q.blocks.filter(g=>g.status!=='hold').length,solo=q.solos.filter(g=>!['done','hold'].includes(g.status)).length;const rows=D.stores.map(store=>{const ps=air.filter(p=>p.store===store);return `<tr><td>${phrase(store)}</td><td>${ps.length}</td><td>${ps.filter(p=>p.active).length}</td><td>${new Set(ps.flatMap(p=>p.cats)).size}</td></tr>`;}).join('');$('#overview-panel').innerHTML=`<div class="overview-intro"><h2>${phrase('同じ商品を、まとめて確認。')}</h2><p>本店・高橋店・採寸用・学校販売・BASEの商品を並べます。サイズだけ違う登録も、一緒に見て判断できます。</p></div><div class="metrics"><div class="metric"><p>2年間に売れた登録</p><strong>2,105</strong></div><div class="metric"><p>未確認の候補</p><strong>${pendingGroups}</strong></div><div class="metric"><p>対応候補なし・未確認</p><strong>${solo}</strong></div></div><section class="overview-section"><h3>確認の進め方</h3><ul><li>上衣・ズボンなど、商品種別ごとに候補の画像・登録元・商品名を見て「全部同じ」を押します。</li><li>違うものがあれば、その商品だけ選びます。分からないものは保留にできます。</li><li>回答は毎回共有保存します。同じブラウザでURLを開くと続きから確認できます。</li><li>学校・色・品番が違う場合は、その違いを確認します。画像がない場合は名称や品番で判断できます。</li></ul><button class="primary" data-start>商品を確認する</button></section><section class="overview-section"><h3>Airレジの商品登録</h3><div class="table-wrap"><table class="store-table"><thead><tr><th>登録元</th><th>全登録</th><th>販売あり</th><th>カテゴリ</th></tr></thead><tbody>${rows}</tbody></table></div><p class="sync-info">全4,031登録・サイズ等33,662行。公開BASE619商品も比較対象です。</p></section><section class="overview-section"><h3>共有の進み具合</h3><p>未確認 ${pendingGroups}グループ ／ 保留 ${q.blocks.filter(g=>g.status==='hold').length}グループ ／ 回答の確認 ${q.blocks.filter(g=>g.status==='conflict').length}グループ</p><p>対応候補のない商品の回答済み ${q.solos.filter(p=>p.status==='done').length}登録 ／ 保留 ${q.solos.filter(p=>p.status==='hold').length}登録</p><p class="sync-info">5秒ごとに更新します。ログインは不要です。確認端末は匿名の番号で記録します。</p></section><section class="overview-section"><h3>今回の対象</h3><p>販売実績は2024年10月1日〜2026年9月30日。商品データは2026年10月2〜3日取得です。売れた商品に対応しそうな、販売記録のない採寸用登録やBASEも並べます。</p><p class="sync-info">「確認する条件」で全商品へ切り替えられます。非公開BASE商品は今回のデータに含まれていません。商品・価格・在庫はこの画面から変更されません。</p></section>`;}
  function render(){if(!D)return;$('#history-open').hidden=session.mode==='history';$('#resume-review').hidden=session.mode!=='history';const q=queues();const count=q.blocks.filter(g=>g.status!=='hold').length;const soloTodo=q.solos.filter(s=>!['done','hold'].includes(s.status)).length;$('#remaining').innerHTML=`残り ${(count+soloTodo).toLocaleString('ja-JP')} 項目<small>同一候補 ${count}組 ／ 対応先の確認 ${soloTodo}登録 ／ 保留 ${q.blocks.filter(g=>g.status==='hold').length+q.solos.filter(s=>s.status==='hold').length}項目</small>`;$('#menu-open').disabled=busy;renderOverview(q);if(view!=='questions')return;
    if(session.mode==='history'){renderHistory();return;}
    if(session.mode==='single'){renderSolos(q);return;}
    const list=eligible(q),total=Math.max(1,Math.ceil(list.length/3));$('#page-label').textContent=`${session.salesOnly?'2年間に売れた商品から':'全商品'}${session.mode==='held'?'・保留した候補':''} ／ ${Math.min(session.page+1,total)} / ${total} ページ`;
    if(!pageBlocks.length){$('#questions').innerHTML='<div class="empty"><h2>この条件の未確認はありません</h2><p>保留や対応候補のない商品は、確認する条件から見ることができます。</p><button data-menu>確認する条件</button></div>';$('#page-actions').innerHTML='';return;}
    $('#questions').innerHTML=pageBlocks.map((g,i)=>{const done=completed.has(g.id),blocked=pending&&!pending.groupIds.includes(g.id);const selected=selection[g.id]||[];const warning=model.warnings(g.members,state);return `<section class="group" data-group="${esc(g.id)}"><div class="group-heading"><h2>${phrase(g.school)}<br>${phrase(g.type)}</h2><span class="group-number">候補 ${session.cursor+i+1}・${g.members.length}登録</span></div>${done?`<div class="saved">保存しました：${phrase(savedGroups.get(g.id)||'回答')}<button data-history>保存した回答を見る</button></div>`:changedGroups.has(g.id)?'<div class="saved">別の端末で回答が更新されました。</div><button data-refresh-candidates>候補を読み直す</button>':`<h3 class="question-title">この商品は、すべて同じですか？</h3><div class="product-grid">${g.members.map(k=>card(k,g,split.has(g.id))).join('')}</div>${warning.length?`<p class="warnings">${esc(warning.join(' ／ '))}</p>`:''}${split.has(g.id)?`<div class="split-actions"><p>違う側の商品を選び、違いを確認してください。</p><p>${selected.length}登録を選択中</p><div class="answerbar"><button data-split-save="different" data-block="${esc(g.id)}" ${busy||blocked||!ready||!selected.length||selected.length===g.members.length?'disabled':''}>別の商品です</button><button data-split-save="family" data-block="${esc(g.id)}" ${busy||blocked||!ready||!selected.length||selected.length===g.members.length?'disabled':''}>同じ型の別仕様です</button><button data-cancel-split="${esc(g.id)}" ${busy?'disabled':''}>選び直す</button></div></div>`:`<div class="answerbar"><button class="primary" data-same="${esc(g.id)}" ${busy||blocked||!ready||warning.length?'disabled':''}>全部同じ</button><button data-split="${esc(g.id)}" ${busy||blocked||!ready?'disabled':''}>違うものを選ぶ</button><button data-hold="${esc(g.id)}" ${busy||blocked||!ready?'disabled':''}>保留</button></div>`}${pending&&!busy?'<p class="warnings">保存を確認できていません。選び直すか、保存をやり直してください。</p>':''}`}</section>`;}).join('');
    const remaining=pageBlocks.filter(g=>!completed.has(g.id));const warnings=remaining.some(g=>changedGroups.has(g.id)||model.warnings(g.members,state).length);$('#page-actions').innerHTML=`<div class="navigation"><button data-page="-1" ${session.cursor===0||busy||pending?'disabled':''}>前のページ</button><button data-page="1" ${busy||pending?'disabled':''}>次の候補へ</button></div>${pending?'<button class="primary" data-retry-save>保存をやり直す</button>':remaining.length>1?`<button class="primary" data-all ${busy||!ready||warnings?'disabled':''}>${phrase('表示中の'+remaining.length+'組は')} ${phrase('それぞれ全部同じ')}</button>`:''}${latest?'<button data-undo>直前の一括回答を取り消す</button>':''}`;layout();
  }
  function renderSolos(q){
    const list=q.solos.filter(s=>s.status!=='done'),total=Math.max(1,Math.ceil(list.length/10));
    const slice=soloBlocks.filter(s=>list.some(x=>x.product.key===s.product.key));
    $('#page-label').textContent=`対応候補のない商品 ／ ${Math.min(session.page+1,total)} / ${total} ページ`;
    $('#questions').innerHTML=slice.length?`<section class="group"><h2>BASEの対応先を確認します</h2><p class="product-school">見つからない場合は「対応先なし」、分からない場合は「保留」を選べます。</p><div class="product-grid">${slice.map(old=>{const s=list.find(x=>x.product.key===old.product.key);return `<div class="solo-wrapper">${card(s.product.key,null)}${s.status==='hold'?'<p class="saved">保留を保存しました</p>':s.status==='conflict'?'<p class="warnings">他の回答との確認が必要です</p>':''}<div class="answerbar"><button data-search-base="${esc(s.product.key)}" ${busy||(pending&&!pending.events.some(e=>e.task==='solo:'+s.product.key))||!ready?'disabled':''}>BASEを探す</button><button data-solo="${esc(s.product.key)}" data-value="unmatched" ${busy||(pending&&!pending.events.some(e=>e.task==='solo:'+s.product.key))||!ready?'disabled':''}>対応先なし</button><button data-solo="${esc(s.product.key)}" data-value="hold" ${busy||(pending&&!pending.events.some(e=>e.task==='solo:'+s.product.key))||!ready?'disabled':''}>保留</button></div></div>`;}).join('')}</div></section>`:'<div class="empty"><h2>この条件の未確認はありません</h2></div>';
    $('#page-actions').innerHTML=`<div class="navigation"><button data-page="-1" ${session.cursor===0||busy||pending?'disabled':''}>前のページ</button><button data-page="1" ${session.cursor+10>=list.length||busy||pending?'disabled':''}>次のページ</button></div>${latest?'<button data-undo>直前の回答を取り消す</button>':''}`;layout();
  }
  function records(){const groups=new Map(),byId=new Map(state.events.map(e=>[e.id,e]));for(const e of [...state.events].sort((a,b)=>b.at.localeCompare(a.at))){const a=groups.get(e.batchId)||[];a.push(e);groups.set(e.batchId,a);}return [...groups].map(([batchId,events])=>{const ids=new Set(events.map(e=>e.id)),tasks=new Set(events.map(e=>e.task));return {batchId,events,before:[...tasks].map(task=>{const ps=[...new Set(events.filter(e=>e.task===task).flatMap(e=>e.parents).filter(id=>!ids.has(id)))].map(id=>byId.get(id));return {task,heads:ps.map(e=>e.id),value:ps.length===1?ps[0].value:null};})};});}
  function eventProducts(e){const pair=model.originalPairs.get(e.task)||state.manualPairs.find(p=>p.key===e.task);return (e.task.startsWith('solo:')?[e.task.slice(5),e.value.target]:pair?[pair.left,pair.right]:[]).filter(k=>model.products.has(k));}
  function historyDecision(e,conflicts){const ps=eventProducts(e).map(k=>model.products.get(k));return `<li><strong>${phrase(ReviewUI.label(e.value))}</strong><p>${ps.map(p=>`${phrase(p.store)}：${phrase(p.name)}`).join(' ／ ')}</p><small>${esc(ReviewUI.current([e],model,state,conflicts))}</small></li>`;}
  function renderHistory(){
    const conflicts=new Set(model.queues(state,{salesOnly:false}).blocks.flatMap(g=>g.edges.filter(e=>e.status==='conflict').map(e=>e.key)));const all=records(),total=Math.max(1,Math.ceil(all.length/25));session.page=Math.min(session.page,total-1);remember();
    const rs=all.slice(session.page*25,session.page*25+25);$('#page-label').textContent=`保存した回答・訂正 ／ ${session.page+1} / ${total} ページ`;
    $('#questions').innerHTML=rs.length?rs.map(r=>{const effective=ReviewUI.batchEvents(r.events),keys=[...new Set(effective.flatMap(eventProducts))],can=r.events.every(e=>model.heads(e.task,state).every(x=>x.batchId===r.batchId));return `<article class="history-row" data-history-batch="${esc(r.batchId)}"><small>${esc(r.events[0].reviewer)}・${esc(new Date(r.events[0].at).toLocaleString('ja-JP'))}</small><h2>${r.events[0].action==='undo'?'取消後の回答：':'保存した回答：'}${phrase(ReviewUI.summary(effective))}</h2><p class="history-current">${esc(ReviewUI.current(effective,model,state,conflicts))}</p><p>${keys.slice(0,4).map(k=>phrase(model.products.get(k).name)).join(' ／ ')}${keys.length>4?' ほか':''}</p><details><summary>商品と回答の内訳を見る（${keys.length}登録）</summary><div class="product-grid">${keys.map(k=>card(k,null)).join('')}</div><ul class="decision-list">${effective.map(e=>historyDecision(e,conflicts)).join('')}</ul></details><button data-undo-batch="${esc(r.batchId)}" ${busy||pending||!ready||!can?'disabled':''}>この回答を取り消す</button></article>`;}).join(''):'<div class="empty"><h2>回答はまだありません</h2></div>';
    $('#page-actions').innerHTML=`<div class="navigation"><button data-page="-1" ${session.page===0||busy||pending?'disabled':''}>前のページ</button><button data-page="1" ${session.page>=total-1||busy||pending?'disabled':''}>次のページ</button></div><button data-resume>商品の確認に戻る</button>`;layout();
  }
  async function api(method,payload,since=false){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(API+(since?'?since='+revision:''),{method,headers:payload?{'Content-Type':'application/json'}:undefined,body:payload?JSON.stringify(payload):undefined,credentials:'omit',cache:'no-store',signal:controller.signal});if(!response.ok)throw Error('保存サービスへ接続できません。');const result=await response.json();if(result.unchanged)return null;const valid=model.validate(result.state);if(payload){const ids=new Map(valid.events.map(e=>[e.id,model.canonical(e)]));if(payload.events.some(e=>ids.get(e.id)!==model.canonical(e)))throw Error('回答の保存を確認できません。');}revision=result.revision;return valid;}finally{clearTimeout(timeout);}}
  async function init(){busy=true;ready=false;mark('共有保存を確認中');error('');try{let store;try{store=localStorage;}catch{store={getItem(){throw Error('端末の控えを利用できません');},setItem(){throw Error('端末の控えを利用できません');}};}storage=window.ReviewPersistence.create(model,store);let local=model.empty();try{local=storage.load();}catch{}try{const prior=storage.readSession();if(prior){session={...session,...prior};if(!prior.resume)delete session.resume;}}catch{}let outbox=null;try{outbox=storage.loadPending();}catch(e){if(e.code==='review_pending_corrupt')throw e;}const remote=await api('GET');state=model.merge(outbox?model.merge(local,outbox):local,remote);const unsaved=model.delta(state,remote);if(unsaved.events.length||unsaved.manualPairs.length)state=await api('POST',unsaved);if(outbox?.events.length){const last=outbox.events.slice().sort((a,b)=>b.at.localeCompare(a.at))[0];savedNotice(outbox.events.filter(e=>e.batchId===last.batchId),true);}notice='';try{storage.commit(state);}catch{notice='回答は共有保存されています。端末の控えは残せません。';}try{storage.clearPending(state);}catch{}pending=null;ready=true;newPage();mark('共有保存済み');error(notice);}catch(e){ready=false;mark('保存に接続できません');error('画面は見られます。回答する前に「確認する条件」から接続をやり直してください。'+(e.code==='review_pending_corrupt'?' 端末の保存待ちの控えは残しています。':''));newPage();}finally{busy=false;render();}}
  function info(){return {uuid:()=>crypto.randomUUID(),batchId:crypto.randomUUID(),at:new Date().toISOString(),reviewer:session.reviewer,evidence:'mixed'};}
  async function commit(result,ids=[]){busy=true;mark('保存中');$('#answer-notice').hidden=true;error('');pending={...result,groupIds:ids,batchId:result.events[0]?.batchId};render();try{try{storage.savePending(result.state,state);}catch{}state=await api('POST',model.delta(result.state,state));notice='';try{storage.commit(state);}catch{notice='共有保存済み。端末の控えは残せません。';}try{storage.clearPending(state);}catch{}latest={batchId:pending.batchId,before:result.before};for(const id of ids){completed.add(id);const g=pageBlocks.find(g=>g.id===id);const es=state.events.filter(e=>{const ks=eventProducts(e);return g&&ks.length===2&&ks.every(k=>g.members.includes(k))&&model.heads(e.task,state).some(h=>h.id===e.id);});savedGroups.set(id,ReviewUI.summary(es));}pending=null;ready=true;savedNotice(result.events);if(session.mode==='single')newPage();session.history=[...session.history,latest.batchId].slice(-50);remember();mark('共有保存済み');error(notice);return true;}catch{mark('保存を確認できていません');error('この回答の保存を確認できません。画面を進めず、保存をやり直すか選び直してください。');return false;}finally{busy=false;render();}}
  function replacePending(result,inScope){if(!pending)return result;const touched=new Set(result.events.map(e=>e.task));const resets=new Map(pending.events.filter(e=>inScope(e.task)&&!touched.has(e.task)).map(e=>[e.task,e.task.startsWith('solo:')?{mapping:'reset'}:{relation:'reset'}]));if(resets.size){const extra=model.append(result.state,resets,result.state.manualPairs,{...info(),batchId:result.events[0].batchId});result.state=extra.state;result.events.push(...extra.events);}const tasks=new Set([...pending.before,...result.before].map(b=>b.task));result.before=[...tasks].map(task=>{const h=model.heads(task,state);return {task,heads:h.map(e=>e.id),value:h.length===1?h[0].value:null};});return result;}
  async function answerBlocks(blocks,relation){if(busy||!ready)return;try{if(blocks.some(g=>changedGroups.has(g.id)))throw Error('別の端末で回答が更新されました。候補を読み直してください。');if(pending&&blocks.some(g=>!pending.groupIds.includes(g.id)))throw Error('保存待ちの組を先に保存してください。');const base=pending?model.merge(state,pending.state):state,eventInfo={...info(),...(pending?{batchId:pending.batchId}:{})},ids=[...new Set([...(pending?.groupIds||[]),...blocks.map(b=>b.id)])];const result=replacePending(model.batch(base,blocks,selection,relation,eventInfo),task=>blocks.some(g=>{const p=model.originalPairs.get(task)||base.manualPairs.find(p=>p.key===task);return p&&g.members.includes(p.left)&&g.members.includes(p.right);}));await commit(result,ids);}catch(e){error(e.message);}}
  async function solo(key,mapping,target){if(busy||!ready)return;try{if(pending&&!pending.events.some(e=>e.task==='solo:'+key))throw Error('保存待ちの商品を先に保存してください。');const base=pending?model.merge(state,pending.state):state,wanted=new Map([['solo:'+key,target?{mapping,target}:{mapping}]]),mp=[...base.manualPairs];if(target){const task=model.pairKey(key,target);wanted.set(task,{relation:'same'});if(!model.originalPairs.has(task)&&!mp.some(p=>p.key===task)){const [left,right]=[key,target].sort();mp.push({key:task,left,right});}}await commit(replacePending(model.append(base,wanted,mp,{...info(),...(pending?{batchId:pending.batchId}:{})}),task=>task==='solo:'+key||task.includes(key)));}catch(e){error(e.message);}}
  async function undo(record){if(!record||busy||!ready||pending)return;try{if(record.before.some(b=>b.heads.length>1))throw Error('以前の回答に食い違いがあります。個別に確認してください。');const result=model.undo(state,record,info());if(await commit(result)){latest=null;newPage();render();}}catch(e){error(e.message);}}
  function openMenu(){if(busy||pending){error('保存待ちの回答を先に保存してください。');return;}for(const k of ['mode','store','school'])$('#'+k).value=session[k];$('#salesOnly').value=session.salesOnly?'yes':'no';$('#menu').showModal();}
  function searchBase(){const term=norm($('#base-search').value);const school=pickerProduct?.cats||[];const ps=D.products.filter(p=>p.source==='base'&&model.compatible(pickerProduct.key,p.key)&&(!term||norm(p.name+p.cats.join('')).includes(term))).sort((a,b)=>Number(b.cats.some(c=>school.includes(c)))-Number(a.cats.some(c=>school.includes(c)))).slice(0,24);$('#base-results').innerHTML=ps.map(p=>card(p.key,null).replace('</article>',`<button class="selection-button" data-link-base="${esc(p.key)}" ${busy?'disabled':''}>同じ商品です</button></article>`)).join('');layout();}
  document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.close){$('#'+b.dataset.close).close();return;}
    if(b.id==='tab-overview')return tab('overview');if(b.id==='tab-questions'||b.hasAttribute('data-start'))return tab('questions');
    if(b.hasAttribute('data-history'))return openHistory();if(b.hasAttribute('data-resume'))return resumeReview();
    if(b.id==='menu-open'||b.hasAttribute('data-menu'))return openMenu();
    if(b.dataset.photo){const p=model.products.get(b.dataset.photo);$('#photo-title').textContent=p.name;$('#photo-image').src=p.imageFull||p.image;$('#photo-image').alt=p.name;$('#photo-source').textContent=p.store+'の登録画像';$('#photo').showModal();return;}
    if(b.dataset.details){const p=model.products.get(b.dataset.details);$('#details-body').innerHTML=`<p>${phrase(p.name)}</p><p>登録元：${esc(p.store)}</p><p>学校・カテゴリ：${phrase(p.cats.join(' / '))}</p><p>レシート名：${phrase(p.receipt||'設定なし')}</p><p>サイズ等 ${p.variantCount}登録：${p.sizes.filter(Boolean).map(phrase).join(' ／ ')||'設定なし'}</p><p class="technical">商品ID ${esc(p.key)}</p>`;$('#details').showModal();return;}
    if(b.dataset.split){split.add(b.dataset.split);selection[b.dataset.split]=[];render();return;}
    if(b.dataset.cancelSplit){split.delete(b.dataset.cancelSplit);selection[b.dataset.cancelSplit]=[];render();return;}
    if(b.dataset.select){const id=b.dataset.block,key=b.dataset.select;const a=new Set(selection[id]||[]);a.has(key)?a.delete(key):a.add(key);selection[id]=[...a];render();return;}
    const block=id=>pageBlocks.find(g=>g.id===id);
    if(b.dataset.same)return answerBlocks([block(b.dataset.same)],'same');if(b.dataset.hold)return answerBlocks([block(b.dataset.hold)],'hold');if(b.dataset.splitSave)return answerBlocks([block(b.dataset.block)],b.dataset.splitSave);
    if(b.hasAttribute('data-all'))return answerBlocks(pageBlocks.filter(g=>!completed.has(g.id)),'same');
    if(b.hasAttribute('data-retry-save'))return pending&&commit(pending,pending.groupIds);
    if(b.hasAttribute('data-undo'))return undo(latest);
    if(b.dataset.undoBatch)return undo(records().find(r=>r.batchId===b.dataset.undoBatch));
    if(b.hasAttribute('data-refresh-candidates')){newPage();render();return;}
    if(b.dataset.page){const step=Number(b.dataset.page);if(session.mode!=='history'){
      const list=currentList(),size=session.mode==='single'?10:3,visible=session.mode==='single'?soloBlocks:pageBlocks;
      const tasks=new Set(visible.flatMap(g=>ReviewUI.tasks(g,session.mode)));
      const positions=list.flatMap((g,i)=>ReviewUI.tasks(g,session.mode).some(t=>tasks.has(t))?[i]:[]);
      const current=ReviewUI.position(list,session);
      const anchor=step>0?(positions.length?Math.max(...positions)+1:current):Math.max(0,current-size);newPage(anchor);
    }else{session.page=Math.max(0,session.page+step);remember();}render();window.scrollTo({top:0,behavior:'smooth'});return;}
    if(b.dataset.solo)return solo(b.dataset.solo,b.dataset.value);
    if(b.dataset.searchBase){pickerProduct=model.products.get(b.dataset.searchBase);$('#base-search').value='';searchBase();$('#picker').showModal();return;}
    if(b.dataset.linkBase){$('#picker').close();return solo(pickerProduct.key,'linked',b.dataset.linkBase);}
    if(b.id==='retry'){$('#menu').close();return init();}
    if(b.id==='export'){const out=pending?model.merge(state,pending.state):state;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.href=url;a.download='勇吉屋_商品確認_'+new Date().toLocaleDateString('sv-SE')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
  });
  $('#settings').addEventListener('submit',e=>{e.preventDefault();
    const nextMode=$('#mode').value;
    if(nextMode==='history'&&session.mode!=='history')session.returnTo={mode:session.mode,page:session.page,cursor:session.cursor,resume:session.resume};
    for(const k of ['mode','store','school'])session[k]=$('#'+k).value;session.salesOnly=$('#salesOnly').value==='yes';session.page=0;session.cursor=0;
    if(nextMode!=='history'){delete session.resume;delete session.returnTo;newPage(0);}else remember();
    $('#menu').close();tab('questions');
  });
  $('#base-search').addEventListener('input',searchBase);for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
  document.addEventListener('toggle',e=>{if(e.target.tagName==='DETAILS')layout();},true);
  addEventListener('resize',layout);addEventListener('beforeunload',e=>{if(busy||pending){e.preventDefault();e.returnValue='';}});
  try{const response=await fetch('data.json',{cache:'no-cache'});if(!response.ok)throw Error();D=await response.json();model=VisualReviewCore.create(D);state=model.empty();for(const store of [...D.stores,'BASE'])$('#store').insertAdjacentHTML('beforeend',`<option value="${esc(store)}">${esc(store)}</option>`);for(const c of [...new Set(D.products.flatMap(p=>p.cats))].sort((a,b)=>a.localeCompare(b,'ja')))$('#school').insertAdjacentHTML('beforeend',`<option value="${esc(c)}">${esc(c)}</option>`);newPage();render();await init();}
  catch{error('商品データを読み込めません。画面を再読み込みしてください。');mark('読み込みに失敗しました');return;}
  setInterval(async()=>{if(!ready||busy||pending||polling||document.hidden)return;polling=true;try{const next=await api('GET',undefined,true);if(next){state=model.merge(state,next);try{storage.commit(state);}catch{}for(const g of pageBlocks)if(!completed.has(g.id)&&pageStamps.get(g.id)!==stamp(g))changedGroups.add(g.id);render();mark('共有の回答を更新しました');}}catch{mark('次の保存時に接続を確認します');}finally{polling=false;}},5000);
})();
